eureka:
  instance:
#    prefer-ip-address: true
    hostname: eurekaServer1
  server:
    renewal-percent-threshold: 0.45
    waitTimeInMsWhenSyncEmpty: 0
  client:
    registerWithEureka: true #作為叢集的話設為true
    fetchRegistry: true #作為叢集的話設為true
    healthcheck:
      enabled: true
    serviceUrl:
      #defaultZone: http://ytc:ytc@${eureka.instance.hostname}:${server.port}/eureka/ ##Eureka Server的位址
      defaultZone: http://ytc:ytc@eurekaServer2:8762/eureka ##Eureka Server的位址
