server:

  port: 8888


spring:

  cloud:

    config:

      server:

        git :

          uri: https://github.com/youngitn/microservices-lab-configuration
          timeout: 4
          skipSslValidation: true